name: medi_camp_plus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.5
  lottie: ^1.4.3
  mysql1: ^0.20.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/lottie/
    - asset/illustrations/
    - asset/icons/
    - asset/fonts/
    - asset/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Bold.ttf
        - asset: asset/fonts/Poppins-Medium.ttf
        - asset: asset/fonts/Poppins-Regular.ttf
        - asset: asset/fonts/Poppins-Thin.ttf
